[package]
name = "lsp"
description = "Async Language Server Protocol client and transport for Mitos"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
categories.workspace = true
repository.workspace = true
homepage.workspace = true

[lib]
name = "lsp_client"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stdx.workspace = true
core.workspace = true
loader.workspace = true
lsp-types.workspace = true
snippets.workspace = true

anyhow.workspace = true
futures-executor.workspace = true
futures-util.workspace = true
globset.workspace = true
log.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["rt", "rt-multi-thread", "io-util", "io-std", "time", "process", "macros", "fs", "parking_lot", "sync"] }
tokio-stream.workspace = true
parking_lot.workspace = true
arc-swap.workspace = true
slotmap.workspace = true
thiserror.workspace = true
sonic-rs.workspace = true
