[package]
name = "vcs"
description = "Version-control status and asynchronous diff support for Mitos"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
categories.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
event.workspace = true
ropey.workspace = true
stdx.workspace = true

tokio = { workspace = true, features = ["rt", "rt-multi-thread", "time", "sync", "parking_lot", "macros"] }
parking_lot.workspace = true
arc-swap.workspace = true

gix = { workspace = true, features = ["attributes", "status", "blame", "parallel", "max-performance", "sha1"], optional = true }
imara-diff.workspace = true
anyhow.workspace = true

log.workspace = true

[features]
git = ["gix"]

[dev-dependencies]
tempfile.workspace = true
