[package]
name = "core"
description = "Core text-editing primitives and language-aware document operations for Mitos"
include = ["src/**/*", "README.md", "LICENSE"]
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
categories.workspace = true
repository.workspace = true
homepage.workspace = true

[lib]
name = "editor_core"

[features]
unicode-lines = ["ropey/unicode_lines"]
integration = []

[dependencies]
stdx.workspace = true
loader.workspace = true
dap-types.workspace = true

ropey.workspace = true
smallvec.workspace = true
smartstring.workspace = true
unicode-segmentation.workspace = true
# unicode-width is changing width definitions
# that both break our logic and disagree with common
# width definitions in terminals, we need to replace it.
# For now lets lock the version to avoid rendering glitches
# when installing without `--locked`
unicode-width.workspace = true
unicode-general-category.workspace = true
slotmap.workspace = true
tree-house.workspace = true
arc-swap.workspace = true
regex.workspace = true
foldhash.workspace = true

log.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
toml.workspace = true

imara-diff.workspace = true
encoding_rs.workspace = true

jiff.workspace = true

textwrap.workspace = true

nucleo.workspace = true
parking_lot.workspace = true
globset.workspace = true
regex-cursor.workspace = true

[dev-dependencies]
tempfile.workspace = true
quickcheck.workspace = true
